### ISSUE TITLE
ListBlock + Wagtail 2.16 throws errors due to changed ListBlock implementation

### ISSUE THREAD

**Issue by mikemonteith-livi** [wagtail/wagtail-transfer#109]
This package expects the json representation of a `ListBlock` to be a `list` of values. Wagtail 2.16 [changed the implementation](https://github.com/wagtail/wagtail/pull/7741) of `ListBlock` so it is now a `list` of `dicts` with a `"value"` key.

**Comment by Scotchester** [comment]
This is the full traceback of the error that I get (which I'm pretty sure is caused by this incompatibility):

```
Internal Server Error: /wagtail-transfer/api/pages/1007/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/wagtail_transfer/views.py", line 49, in pages_for_export
    object_references.update(serializer.get_object_references(model))
  File "/usr/local/lib/python3.8/dist-packages/wagtail_transfer/serializers.py", line 150, in get_object_references
    refs = super().get_object_references(instance)
  File "/usr/local/lib/python3.8/dist-packages/wagtail_transfer/serializers.py", line 127, in get_object_references
    refs.update(f.get_object_references(instance))
  File "/usr/local/lib/python3.8/dist-packages/wagtail_transfer/field_adapters.py", line 265, in get_object_references
    return get_object_references(self.stream_block, stream)
  File "/usr/local/lib/python3.8/dist-packages/wagtail_transfer/streamfield.py", line 34, in get_object_references
    stream_block_handler.map_over_json(stream, get_references)
  File "/usr/local/lib/python3.8/dist-packages/wagtail_transfer/streamfield.py", line 110, in map_over_json
    new_value = new_block_handler.map_over_json(new_stream, func)
  File "/usr/local/lib/python3.8/dist-packages/wagtail_transfer/streamfield.py", line 134, in map_over_json
    new_value = new_block_handler.map_over_json(new_stream, func)
  File "/usr/local/lib/python3.8/dist-packages/wagtail_transfer/streamfield.py", line 91, in map_over_json
    new_value = new_block_handler.map_over_json(element, func)
  File "/usr/local/lib/python3.8/dist-packages/wagtail_transfer/streamfield.py", line 134, in map_over_json
    new_value = new_block_handler.map_over_json(new_stream, func)
  File "/usr/local/lib/python3.8/dist-packages/wagtail_transfer/streamfield.py", line 79, in map_over_json
    if self.block.required and value is None:
AttributeError: 'NoneType' object has no attribute 'required'
```

If I remove all items from the one `ListBlock` on the page, the error goes away.

**Comment by gasman** [comment]
I'm unable to replicate this on a pair of test instances running under Wagtail main with the following models file:

```python
from django.db import models

from wagtail.core import blocks
from wagtail.core.models import Page
from wagtail.admin.edit_handlers import PageChooserPanel, StreamFieldPanel
from wagtail.core.fields import StreamField


class HomePage(Page):
    body = StreamField([
        ('title', blocks.CharBlock()),
        ('bullet_list', blocks.ListBlock(blocks.CharBlock())),
    ], null=True, blank=True)
    featured_page = models.ForeignKey(
        'wagtailcore.Page', null=True, blank=True, on_delete=models.SET_NULL,
        related_name='+'
    )

    content_panels = Page.content_panels + [
        StreamFieldPanel('body'),
        PageChooserPanel('featured_page'),
    ]
```
Maybe the issue only occurs for ListBlock data created on Wagtail <2.16?

**Comment by mikemonteith-livi** [comment]
It looks like this bug only manifests when there is more complicated data type inside the list.

I have managed to replicate with this:
```
from django.db import models

from wagtail.core import blocks
from wagtail.core.models import Page
from wagtail.admin.edit_handlers import PageChooserPanel, StreamFieldPanel
from wagtail.core.fields import StreamField


class MyBlock(blocks.StructBlock):
    name = blocks.CharBlock()
    description = blocks.CharBlock()

class HomePage(Page):
    body = StreamField([
        ('title', blocks.CharBlock()),
        ('my_list', blocks.ListBlock(MyBlock())),
    ], null=True, blank=True)
    featured_page = models.ForeignKey(
        'wagtailcore.Page', null=True, blank=True, on_delete=models.SET_NULL,
        related_name='+'
    )

    content_panels = Page.content_panels + [
        StreamFieldPanel('body'),
        PageChooserPanel('featured_page'),
    ]

```

This is with a clean install of Wagtail 2.16.2
