### ISSUE TITLE
Support Wagtail 4.0?

### ISSUE THREAD

**Issue by pdeero** [wagtail/wagtail-transfer#131]
Dear guys,

does the version 0.8.5 supports wagtail 4.0? 

Cause if i'm trying to import an example page to the destination instance. While the transfer i'm receiving an error which says:
’’’
[2022-12-08 13:04:15 +0000] [80] [DEBUG] POST /admin/wagtail-transfer/import/
--
Thu, Dec 8 2022 2:04:16 pm | 2022-12-08 13:04:16,263 ERROR [django.request:241] log 80 139729784517632 Internal Server Error: /admin/wagtail-transfer/import/
Thu, Dec 8 2022 2:04:16 pm | Traceback (most recent call last):
Thu, Dec 8 2022 2:04:16 pm | File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
Thu, Dec 8 2022 2:04:16 pm | response = get_response(request)
Thu, Dec 8 2022 2:04:16 pm | File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
Thu, Dec 8 2022 2:04:16 pm | response = wrapped_callback(request, *callback_args, **callback_kwargs)
Thu, Dec 8 2022 2:04:16 pm | File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/django/views.py", line 68, in sentry_wrapped_callback
Thu, Dec 8 2022 2:04:16 pm | return callback(request, *args, **kwargs)
Thu, Dec 8 2022 2:04:16 pm | File "/usr/local/lib/python3.8/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
Thu, Dec 8 2022 2:04:16 pm | response = view_func(request, *args, **kwargs)
Thu, Dec 8 2022 2:04:16 pm | File "/usr/local/lib/python3.8/site-packages/wagtail/admin/urls/__init__.py", line 170, in wrapper
Thu, Dec 8 2022 2:04:16 pm | return view_func(request, *args, **kwargs)
Thu, Dec 8 2022 2:04:16 pm | File "/usr/local/lib/python3.8/site-packages/wagtail/admin/auth.py", line 182, in decorated_view
Thu, Dec 8 2022 2:04:16 pm | response = view_func(request, *args, **kwargs)
Thu, Dec 8 2022 2:04:16 pm | File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
Thu, Dec 8 2022 2:04:16 pm | return view_func(request, *args, **kwargs)
Thu, Dec 8 2022 2:04:16 pm | File "/usr/local/lib/python3.8/site-packages/django/views/decorators/http.py", line 43, in inner
Thu, Dec 8 2022 2:04:16 pm | return func(request, *args, **kwargs)
Thu, Dec 8 2022 2:04:16 pm | File "/usr/local/lib/python3.8/site-packages/wagtail_transfer/views.py", line 304, in do_import
Thu, Dec 8 2022 2:04:16 pm | return import_page(request)
Thu, Dec 8 2022 2:04:16 pm | File "/usr/local/lib/python3.8/site-packages/wagtail_transfer/views.py", line 267, in import_page
Thu, Dec 8 2022 2:04:16 pm | importer.add_json(response.content)
Thu, Dec 8 2022 2:04:16 pm | File "/usr/local/lib/python3.8/site-packages/wagtail_transfer/operations.py", line 217, in add_json
Thu, Dec 8 2022 2:04:16 pm | data = json.loads(json_data)
Thu, Dec 8 2022 2:04:16 pm | File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
Thu, Dec 8 2022 2:04:16 pm | return _default_decoder.decode(s)
Thu, Dec 8 2022 2:04:16 pm | File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
Thu, Dec 8 2022 2:04:16 pm | obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Thu, Dec 8 2022 2:04:16 pm | File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
Thu, Dec 8 2022 2:04:16 pm | raise JSONDecodeError("Expecting value", s, err.value) from None
Thu, Dec 8 2022 2:04:16 pm | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
’’’

’’’
[2022-12-08 13:06:56 +0000] [81] [DEBUG] POST /admin/wagtail-transfer/import/
--
Thu, Dec 8 2022 2:06:57 pm | 2022-12-08 13:06:57,713 ERROR [django.request:241] log 81 139729771945632 Internal Server Error: /admin/wagtail-transfer/import/
Thu, Dec 8 2022 2:06:57 pm | Traceback (most recent call last):
Thu, Dec 8 2022 2:06:57 pm | File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
Thu, Dec 8 2022 2:06:57 pm | response = get_response(request)
Thu, Dec 8 2022 2:06:57 pm | File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
Thu, Dec 8 2022 2:06:57 pm | response = wrapped_callback(request, *callback_args, **callback_kwargs)
Thu, Dec 8 2022 2:06:57 pm | File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/django/views.py", line 68, in sentry_wrapped_callback
Thu, Dec 8 2022 2:06:57 pm | return callback(request, *args, **kwargs)
Thu, Dec 8 2022 2:06:57 pm | File "/usr/local/lib/python3.8/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
Thu, Dec 8 2022 2:06:57 pm | response = view_func(request, *args, **kwargs)
Thu, Dec 8 2022 2:06:57 pm | File "/usr/local/lib/python3.8/site-packages/wagtail/admin/urls/__init__.py", line 170, in wrapper
Thu, Dec 8 2022 2:06:57 pm | return view_func(request, *args, **kwargs)
Thu, Dec 8 2022 2:06:57 pm | File "/usr/local/lib/python3.8/site-packages/wagtail/admin/auth.py", line 182, in decorated_view
Thu, Dec 8 2022 2:06:57 pm | response = view_func(request, *args, **kwargs)
Thu, Dec 8 2022 2:06:57 pm | File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
Thu, Dec 8 2022 2:06:57 pm | return view_func(request, *args, **kwargs)
Thu, Dec 8 2022 2:06:57 pm | File "/usr/local/lib/python3.8/site-packages/django/views/decorators/http.py", line 43, in inner
Thu, Dec 8 2022 2:06:57 pm | return func(request, *args, **kwargs)
Thu, Dec 8 2022 2:06:57 pm | File "/usr/local/lib/python3.8/site-packages/wagtail_transfer/views.py", line 304, in do_import
Thu, Dec 8 2022 2:06:57 pm | return import_page(request)
Thu, Dec 8 2022 2:06:57 pm | File "/usr/local/lib/python3.8/site-packages/wagtail_transfer/views.py", line 268, in import_page
Thu, Dec 8 2022 2:06:57 pm | importer = import_missing_object_data(source, importer)
Thu, Dec 8 2022 2:06:57 pm | File "/usr/local/lib/python3.8/site-packages/wagtail_transfer/views.py", line 254, in import_missing_object_data
Thu, Dec 8 2022 2:06:57 pm | importer.run()
Thu, Dec 8 2022 2:06:57 pm | File "/usr/local/lib/python3.8/site-packages/wagtail_transfer/operations.py", line 467, in run
Thu, Dec 8 2022 2:06:57 pm | self._add_to_operation_order(operation, operation_order, [operation])
Thu, Dec 8 2022 2:06:57 pm | File "/usr/local/lib/python3.8/site-packages/wagtail_transfer/operations.py", line 576, in _add_to_operation_order
Thu, Dec 8 2022 2:06:57 pm | self._add_to_operation_order(resolution, operation_order, path + [resolution])
Thu, Dec 8 2022 2:06:57 pm | File "/usr/local/lib/python3.8/site-packages/wagtail_transfer/operations.py", line 572, in _add_to_operation_order
Thu, Dec 8 2022 2:06:57 pm | raise CircularDependencyException()
Thu, Dec 8 2022 2:06:57 pm | wagtail_transfer.operations.CircularDependencyException

’’’

**Comment by gasman** [comment]
Formal support for Wagtail 4.0 was added in 0.8.6. Not sure if the issues here are related to version compatibility, but without any steps to reproduce it's impossible to confirm either way.
