### ISSUE TITLE
Bug/clash with wagtailmedia

### ISSUE THREAD

**Issue by stevejalim** [wagtail/wagtail-transfer#49]
When transferring a video from `wagtailmedia` that doesn't have the _optional_ thumbnail image specified, the transfer will fail hard with a server error.

### How to reproduce

**On your source and target:**
* Have `wagtailmedia` as an INSTALLED APPS
* Have a Page type that allows inclusion of a video (eg a simple Video Block)

**On the source:**
* Add a Video (A) to the media library with no thumbnail - but don't feature it in a page
* Run `preseed_transfer_table` with `wagtailmedia` (ie, it's an app level mention, not a specific model within `wagtailmedia` 
* Add another Video (B) to the page with no thumbnail 
* Include Video B in a page, and publish it

**On the target side:**
* Import the page that has the video with no thumbnail embedded in it.

**What should happen:**
* The page and the newly-uploaded Video B should have been cloned to the target site

**What actually happens:**
* both source and targets throw 500s

**Note that if Video B _then_ has a thumbnail associated with it on the source server and the transfer is attempted again, it will now succeed.**

**Example source-server traceback**
```
127.0.0.1 - - [15/Sep/2020 10:10:12] "POST /wagtail-transfer/api/objects/?digest=d5b38253f236fb8456768f2a5a1fb22e6aebeca5 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/path/to/venv/redacted/lib/python3.6/site-packages/django/contrib/staticfiles/handlers.py", line 65, in __call__
    return self.application(environ, start_response)
  File "/path/to/venv/redacted/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
  File "/path/to/venv/redacted/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
  File "/path/to/venv/redacted/lib/python3.6/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/path/to/venv/redacted/lib/python3.6/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/path/to/venv/redacted/lib/python3.6/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/path/to/venv/redacted/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 37, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/path/to/venv/redacted/lib/python3.6/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/path/to/venv/redacted/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/path/to/venv/redacted/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/path/to/venv/redacted/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/path/to/venv/redacted/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/path/to/venv/redacted/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/path/to/venv/redacted/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/path/to/venv/redacted/lib/python3.6/site-packages/wagtail_transfer/views.py", line 129, in objects_for_export
    objects.append(serializer.serialize(obj))
  File "/path/to/venv/redacted/lib/python3.6/site-packages/wagtail_transfer/serializers.py", line 61, in serialize
    'fields': self.serialize_fields(instance)
  File "/path/to/venv/redacted/lib/python3.6/site-packages/wagtail_transfer/serializers.py", line 54, in serialize_fields
    for field_adapter in self.field_adapters
  File "/path/to/venv/redacted/lib/python3.6/site-packages/wagtail_transfer/serializers.py", line 54, in <dictcomp>
    for field_adapter in self.field_adapters
  File "/path/to/venv/redacted/lib/python3.6/site-packages/wagtail_transfer/field_adapters.py", line 167, in serialize
    url = self.field.value_from_object(instance).url
  File "/path/to/venv/redacted/lib/python3.6/site-packages/django/db/models/fields/files.py", line 61, in url
    self._require_file()
  File "/path/to/venv/redacted/lib/python3.6/site-packages/django/db/models/fields/files.py", line 38, in _require_file
    raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)
ValueError: The 'thumbnail' attribute has no file associated with it.
```

**Example source-server traceback**
```
127.0.0.1 - - [15/Sep/2020 10:10:13] "POST /admin/wagtail-transfer/import/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/path/to/venv/redacted/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
StopIteration: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/to/venv/redacted/lib/python3.6/site-packages/django/contrib/staticfiles/handlers.py", line 65, in __call__
    return self.application(environ, start_response)
  File "/path/to/venv/redacted/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
  File "/path/to/venv/redacted/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
  File "/path/to/venv/redacted/lib/python3.6/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/path/to/venv/redacted/lib/python3.6/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/path/to/venv/redacted/lib/python3.6/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/path/to/venv/redacted/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 37, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/path/to/venv/redacted/lib/python3.6/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/path/to/venv/redacted/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/path/to/venv/redacted/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/path/to/venv/redacted/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/path/to/venv/redacted/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/path/to/venv/redacted/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/path/to/venv/redacted/lib/python3.6/site-packages/wagtail/admin/urls/__init__.py", line 110, in wrapper
    return view_func(request, *args, **kwargs)
  File "/path/to/venv/redacted/lib/python3.6/site-packages/wagtail/admin/auth.py", line 188, in decorated_view
    return view_func(request, *args, **kwargs)
  File "/path/to/venv/redacted/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/path/to/venv/redacted/lib/python3.6/site-packages/wagtail_transfer/views.py", line 267, in do_import
    return import_page(request)
  File "/path/to/venv/redacted/lib/python3.6/site-packages/wagtail_transfer/views.py", line 234, in import_page
    importer = import_missing_object_data(source, importer)
  File "/path/to/venv/redacted/lib/python3.6/site-packages/wagtail_transfer/views.py", line 219, in import_missing_object_data
    importer.add_json(response.content)
  File "/path/to/venv/redacted/lib/python3.6/site-packages/wagtail_transfer/operations.py", line 207, in add_json
    data = json.loads(json_data)
  File "/path/to/venv/redacted/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/path/to/venv/redacted/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/path/to/venv/redacted/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by stevejalim** [comment]
This was fixed by the change released on 0.5.1 - thanks @jacobtoppm
