### ISSUE TITLE
Integrity Error: Key (language_code)=(en) already exists

### ISSUE THREAD

**Issue by mel-mason** [wagtail/wagtail-transfer#69]
Hi,

I just started testing the transfer tool - running it between two dev instances running on the same machine. I tried to import the home page (so the whole site, ~135 pages) of one instance to a fresh instance of our site with no pages added, just the default wagtail homepage. It all seemed to connect fine, but after a while of transferring I got an error: 

IntegrityError at /cms/wagtail-transfer/import/

duplicate key value violates unique constraint "wagtailcore_locale_language_code_key"
DETAIL:  Key (language_code)=(en) already exists.

(More details and traceback below)

I've tried to fix this by altering my settings without success - I get the same error whether or not I include 'locale' lookup fields:

```
WAGTAILTRANSFER_LOOKUP_FIELDS = {'content.partner': ['name'], 'content.collection': ['name'], 'content.exhibition': ['name'], 'wagtail.locale': ['language_code']
    , 'wagtailcore.locale': ['language_code'], 'wagtail.core.locale': ['language_code'], 'locale': ['language_code']}
```
(I wasn't sure what app label to use for the class, as you can tell, so thought I would try them all)

Any ideas what I should investigate next? Thanks in advance for any help you can give.

## Details

I have no other wagtail transfer settings beyond the secret key and backends.

Both sites are running:
wagtail==2.11.3
wagtail-transfer==0.6.0

```
Environment:


Request Method: POST
Request URL: http://localhost:8001/cms/wagtail-transfer/import/

Django Version: 3.0.11
Python Version: 3.6.9
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'django.contrib.sitemaps',
 'rest_framework',
 'rest_framework.authtoken',
 'django_extensions',
 'discovery',
 'discovery.content',
 'discovery.data',
 'django_jinja',
 'django_jinja.contrib._humanize',
 'wagtail.contrib.forms',
 'wagtail.contrib.redirects',
 'wagtail.contrib.postgres_search',
 'wagtail.embeds',
 'wagtail.sites',
 'wagtail.users',
 'wagtail.snippets',
 'wagtail.documents',
 'wagtail.images',
 'wagtail.search',
 'wagtail.admin',
 'wagtail.core',
 'wagtail_transfer',
 'social_django',
 'modelcluster',
 'taggit',
 'cachalot',
 'debug_toolbar']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'wagtail.contrib.redirects.middleware.RedirectMiddleware',
 'debug_toolbar.middleware.DebugToolbarMiddleware']



Traceback (most recent call last):
  File "/home/mel/Code/discovery_server_second/.venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)

The above exception (duplicate key value violates unique constraint "wagtailcore_locale_language_code_key"
DETAIL:  Key (language_code)=(en) already exists.
) was the direct cause of the following exception:
  File "/home/mel/Code/discovery_server_second/.venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/mel/Code/discovery_server_second/.venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mel/Code/discovery_server_second/.venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mel/Code/discovery_server_second/.venv/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/mel/Code/discovery_server_second/.venv/lib/python3.6/site-packages/wagtail/admin/urls/__init__.py", line 127, in wrapper
    return view_func(request, *args, **kwargs)
  File "/home/mel/Code/discovery_server_second/.venv/lib/python3.6/site-packages/wagtail/admin/auth.py", line 193, in decorated_view
    return view_func(request, *args, **kwargs)
  File "/home/mel/Code/discovery_server_second/.venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/home/mel/Code/discovery_server_second/.venv/lib/python3.6/site-packages/wagtail_transfer/views.py", line 284, in do_import
    return import_page(request)
  File "/home/mel/Code/discovery_server_second/.venv/lib/python3.6/site-packages/wagtail_transfer/views.py", line 251, in import_page
    importer = import_missing_object_data(source, importer)
  File "/home/mel/Code/discovery_server_second/.venv/lib/python3.6/site-packages/wagtail_transfer/views.py", line 237, in import_missing_object_data
    importer.run()
  File "/home/mel/Code/discovery_server_second/.venv/lib/python3.6/site-packages/wagtail_transfer/operations.py", line 463, in run
    operation.run(self.context)
  File "/home/mel/Code/discovery_server_second/.venv/lib/python3.6/site-packages/wagtail_transfer/operations.py", line 678, in run
    self._save(context)
  File "/home/mel/Code/discovery_server_second/.venv/lib/python3.6/site-packages/wagtail_transfer/operations.py", line 641, in _save
    self.instance.save()
  File "/home/mel/Code/discovery_server_second/.venv/lib/python3.6/site-packages/django/db/models/base.py", line 749, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/mel/Code/discovery_server_second/.venv/lib/python3.6/site-packages/django/db/models/base.py", line 787, in save_base
    force_update, using, update_fields,
  File "/home/mel/Code/discovery_server_second/.venv/lib/python3.6/site-packages/django/db/models/base.py", line 890, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/home/mel/Code/discovery_server_second/.venv/lib/python3.6/site-packages/django/db/models/base.py", line 929, in _do_insert
    using=using, raw=raw,
  File "/home/mel/Code/discovery_server_second/.venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mel/Code/discovery_server_second/.venv/lib/python3.6/site-packages/django/db/models/query.py", line 1204, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/mel/Code/discovery_server_second/.venv/lib/python3.6/site-packages/cachalot/monkey_patch.py", line 29, in inner
    return original(compiler, *args, **kwargs)
  File "/home/mel/Code/discovery_server_second/.venv/lib/python3.6/site-packages/cachalot/monkey_patch.py", line 101, in inner
    return original(write_compiler, *args, **kwargs)
  File "/home/mel/Code/discovery_server_second/.venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1394, in execute_sql
    cursor.execute(sql, params)
  File "/home/mel/Code/discovery_server_second/.venv/lib/python3.6/site-packages/debug_toolbar/panels/sql/tracking.py", line 198, in execute
    return self._record(self.cursor.execute, sql, params)
  File "/home/mel/Code/discovery_server_second/.venv/lib/python3.6/site-packages/debug_toolbar/panels/sql/tracking.py", line 133, in _record
    return method(sql, params)
  File "/home/mel/Code/discovery_server_second/.venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/mel/Code/discovery_server_second/.venv/lib/python3.6/site-packages/cachalot/monkey_patch.py", line 125, in inner
    return original(cursor, sql, *args, **kwargs)
  File "/home/mel/Code/discovery_server_second/.venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/mel/Code/discovery_server_second/.venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/mel/Code/discovery_server_second/.venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mel/Code/discovery_server_second/.venv/lib/python3.6/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/mel/Code/discovery_server_second/.venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)

Exception Type: IntegrityError at /cms/wagtail-transfer/import/
Exception Value: duplicate key value violates unique constraint "wagtailcore_locale_language_code_key"
DETAIL:  Key (language_code)=(en) already exists.

```

**Comment by mel-mason** [comment]
Snippets import fine, but none of the pages will, even a simple about page with no children. I get the same error if I remove the WAGTAILTRANSFER_LOOKUP_FIELDS setting, or change it to only have 'wagtailcore.locale' as the key.

Adding `WAGTAILTRANSFER_NO_FOLLOW_MODELS = ['wagtailcore.page', 'wagtailcore.locale']` gave me an AssertionError on the Locale model first time, and a silent failure on subsequent attempts - pressing import just redirected to the home page, with no change to page.  This happens with or without the WAGTAILTRANSFER_LOOKUP_FIELDS 

I've never altered locales on either site - the site is only available in English.

**Comment by jacobtoppm** [comment]
Hi,

That's very odd! The basic settings do need an update for 2.11 based on this, but `"wagtailcore.locale": ["language_code"]` in the `WAGTAILTRANSFER_LOOKUP_FIELDS` setting should work (and is the config I use for a 2.11 setup). Just to confirm, do you have `WAGTAILTRANSFER_LOOKUP_FIELDS` set to the same value on both instances?

**Comment by jacobtoppm** [comment]
To check that you're getting the right locator for the model, in the Django shell you could try:

```
from wagtail.core.models import Locale
from wagtail_transfer.locators import get_locator_for_model

get_locator_for_model(Locale)

```

Do you get an instance of `FieldLocator`, or of `IDMappingLocator` on both sites?

**Comment by mel-mason** [comment]
Thanks! The problem was that I didn't have the WAGTAILTRANSFER_LOOKUP_FIELDS set to the same value on both - I had assumed it would only be the importing instance that needed that setting. (Might be worth specifying that in the README?). It's all working perfectly with `WAGTAILTRANSFER_LOOKUP_FIELDS={"wagtailcore.locale": ["language_code"]}`

**Comment by jacobtoppm** [comment]
No problem! Yes, I'll see if I can get that in - all settings/transfer-related code, except for the secret key and sources list, should be shared between instances so the sites communicate properly.
