### ISSUE TITLE
KeyError on importing a page containing a reference to a grandchild page

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail-transfer#84]
If a page contains a ForeignKey or StreamField reference to a grandchild page of itself, importing that page throws a KeyError referring to the page at the intermediate level between them.

Steps to reproduce:

```
mkvirtualenv wagtailtransfertest --python=python3.8
pip install wagtail==2.12.4 wagtail-transfer==0.7.1
wagtail start transfer1
```

In transfer1/transfer1/settings/base.py, add 'wagtail_transfer' to INSTALLED_APPS and add:

```
WAGTAILTRANSFER_SOURCES = {
    'transfer2': {
        'BASE_URL': 'http://localhost:8001/wagtail-transfer/',
        'SECRET_KEY': '4ac4822149691395773b2a8942e1a472',
    },
}

WAGTAILTRANSFER_SECRET_KEY = '7cd5de8229be75e1e0c2af8abc2ada7e'
```

In transfer1/transfer1/urls.py, add:

```
from wagtail_transfer import urls as wagtailtransfer_urls
from django.conf.urls import url

# inside the first urlpatterns block:
    url(r'^wagtail-transfer/', include(wagtailtransfer_urls)),
```

Edit transfer1/home/models.py to:
```
from django.db import models

from wagtail.core.models import Page
from wagtail.admin.edit_handlers import PageChooserPanel


class HomePage(Page):
    featured_page = models.ForeignKey(
        'wagtailcore.Page', null=True, blank=True, on_delete=models.SET_NULL,
        related_name='+'
    )

    content_panels = Page.content_panels + [
        PageChooserPanel('featured_page'),
    ]
```

Set up and pre-seed the database:
```
cd transfer1
./manage.py makemigrations
./manage.py migrate
./manage.py createsuperuser
./manage.py preseed_transfer_table auth wagtailcore
```

Clone the project as transfer2:
```
cd ..
cp -pr transfer1 transfer2
```

Edit transfer2/transfer1/settings/base.py:

```
WAGTAILTRANSFER_SOURCES = {
    'transfer1': {
        'BASE_URL': 'http://localhost:8000/wagtail-transfer/',
        'SECRET_KEY': '7cd5de8229be75e1e0c2af8abc2ada7e',
    },
}

WAGTAILTRANSFER_SECRET_KEY = '4ac4822149691395773b2a8942e1a472'
```

Start the transfer1 project on port 8000:
```
cd transfer1
./manage.py runserver 0:8000
```

In another terminal, start the transfer2 project on port 8001:
```
workon wagtailtransfertest
cd transfer2
./manage.py runserver 0:8001
```

* Log in to http://localhost:8000/admin/
* Create and publish a subpage of Home named level1 (with 'Featured Page' left empty).
* Create and publish a subpage of level1 named level2 (with 'Featured Page' left empty).
* Create and publish a subpage of level2 named level3 (with 'Featured Page' left empty).
* Edit level1, select level3 as the featured page, and publish.
* In an incognito tab, log in to http://localhost:8001/admin/
* Go to Import; select transfer1 as the source site, level1 as parent page, and Home as destination

Importing fails with:

```
KeyError at /admin/wagtail-transfer/import/
(<class 'wagtail.core.models.Page'>, 5)

Request Method: POST
Request URL: http://localhost:8001/admin/wagtail-transfer/import/

Django Version: 3.1.10
Python Version: 3.8.0
Installed Applications:
['home',
 'search',
 'wagtail.contrib.forms',
 'wagtail.contrib.redirects',
 'wagtail.embeds',
 'wagtail.sites',
 'wagtail.users',
 'wagtail.snippets',
 'wagtail.documents',
 'wagtail.images',
 'wagtail.search',
 'wagtail.admin',
 'wagtail.core',
 'modelcluster',
 'taggit',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'wagtail_transfer']
Installed Middleware:
['django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'wagtail.contrib.redirects.middleware.RedirectMiddleware']



Traceback (most recent call last):
  File "/Users/matthew/.virtualenvs/wagtailtransfertest/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/matthew/.virtualenvs/wagtailtransfertest/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/matthew/.virtualenvs/wagtailtransfertest/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/matthew/.virtualenvs/wagtailtransfertest/lib/python3.8/site-packages/wagtail/admin/urls/__init__.py", line 127, in wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/matthew/.virtualenvs/wagtailtransfertest/lib/python3.8/site-packages/wagtail/admin/auth.py", line 193, in decorated_view
    return view_func(request, *args, **kwargs)
  File "/Users/matthew/.virtualenvs/wagtailtransfertest/lib/python3.8/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/Users/matthew/.virtualenvs/wagtailtransfertest/lib/python3.8/site-packages/wagtail_transfer/views.py", line 284, in do_import
    return import_page(request)
  File "/Users/matthew/.virtualenvs/wagtailtransfertest/lib/python3.8/site-packages/wagtail_transfer/views.py", line 251, in import_page
    importer = import_missing_object_data(source, importer)
  File "/Users/matthew/.virtualenvs/wagtailtransfertest/lib/python3.8/site-packages/wagtail_transfer/views.py", line 237, in import_missing_object_data
    importer.run()
  File "/Users/matthew/.virtualenvs/wagtailtransfertest/lib/python3.8/site-packages/wagtail_transfer/operations.py", line 463, in run
    operation.run(self.context)
  File "/Users/matthew/.virtualenvs/wagtailtransfertest/lib/python3.8/site-packages/wagtail_transfer/operations.py", line 678, in run
    self._save(context)
  File "/Users/matthew/.virtualenvs/wagtailtransfertest/lib/python3.8/site-packages/wagtail_transfer/operations.py", line 716, in _save
    self.destination_parent_id = context.destination_ids_by_source[(get_base_model(self.model), source_parent_id)]

Exception Type: KeyError at /admin/wagtail-transfer/import/
Exception Value: (<class 'wagtail.core.models.Page'>, 5)
```

Note that page ID 5 is the 'level2' page.

**Comment by gasman** [comment]
I now have a clear idea of why this is happening:

By the time we call [`ImportPlanner.run()`](https://github.com/wagtail/wagtail-transfer/blob/933d69e0100aea63490663021be507d346e5f23d/wagtail_transfer/operations.py#L444), it's correctly determined that:
* creating level1 has a soft dependency on level3
* creating level2 has a hard dependency on level1
* creating level3 has a hard dependency on level2

`_check_satisfiable` confirms that all of these operations are satisfiable
(because it only considers hard dependencies, and in those the dependency chain ends at level1).

The problem is with `_add_to_operation_order`, which does try to respect soft dependencies where possible.
If the first operation it considers is creating level2, then:
* it sees the hard dependency on level1, so recursively calls _add_to_operation_order on the 'create level1' operation
* it sees the soft dependency on level3, and at this point there's no indication that it can't be satisfied, so recursively calls `_add_to_operation_order` on the 'create level3' operation
* it sees the hard dependency on level2, and observes that the 'create level2' operation was part of the path it took to get here, so it's detected a circular dependency

The code wrongly assumes that the last dependency we encounter is the soft one, so it thinks it's OK to break the chain here. As a result, it chooses to create level2 before level1 exists.

Incidentally, I think the `except KeyError:` logic might also be (harmlessly) incorrect: it's based on the misconception that the previous `_check_satisfiable` step was populating the resolutions lookup table, and so any failed lookups must be soft dependencies (which `_check_satisfiable` ignores). In fact, the resolutions lookup table is populated during the earlier phase of doing API calls, so this lookup will always succeed even for soft dependencies. This is just as well, because if it does follow the `except KeyError` code path, it'll end up leaving the variable 'resolution' unset (causing it to either fail with 'variable used before definition', or to hold on to the value from the previous iteration).

**Comment by gasman** [comment]
> Incidentally, I think the except KeyError: logic might also be (harmlessly) incorrect: it's based on the misconception that the previous _check_satisfiable step was populating the resolutions lookup table, and so any failed lookups must be soft dependencies (which _check_satisfiable ignores). In fact, the resolutions lookup table is populated during the earlier phase of doing API calls, so this lookup will always succeed even for soft dependencies. This is just as well, because if it does follow the except KeyError code path, it'll end up leaving the variable 'resolution' unset (causing it to either fail with 'variable used before definition', or to hold on to the value from the previous iteration).

No, I'm wrong here. I was thrown off by the unintuitive meaning of `continue` - i.e. "forget about trying to satisfy this soft dependency and move on to the next iteration of the loop to check the next dependency", not "continue to the `if resolution is None` logic below". This try/except comes in to play when (for example) a page we're importing contains a rich text link to a page outside of the tree to be imported - in which case

* there is no resolution for that linked page, but instead [it's recorded in `failed_creations`](https://github.com/wagtail/wagtail-transfer/blob/933d69e0100aea63490663021be507d346e5f23d/wagtail_transfer/operations.py#L289-L290)
* it's a soft dependency, otherwise we would have [spotted it during `_check_satisfiable`](https://github.com/wagtail/wagtail-transfer/blob/933d69e0100aea63490663021be507d346e5f23d/wagtail_transfer/operations.py#L502) and abandoned that whole line as unsatisfiable.

**Comment by sheralim012** [comment]
After updating to the latest version I am randomly getting `CircularDependencyException` with the example above 
and it is the exact use case for the project I’m currently working on
the thing I observed is that for the same data being imported order of operations is random (you can see it by simply printing the operations and their dependencies) 
and importing only succeed if operations are in correct order otherwise `CircularDependencyException` is raised

any idea @jacobtoppm

**Comment by jacobtoppm** [comment]
Hi @sheralim012 - could you confirm if your use case is exactly the example above (ie, is the reference a `ForeignKey`, and is it nullable), or just similar (in which case, could you let me know what form the reference takes, and ideally the models file)?

**Comment by sheralim012** [comment]
Thanks for such a swift response
the project is [Unicef IoGT](https://github.com/unicef/iogt) 
and the case I'm referring to can be seen [here](https://github.com/unicef/iogt/blob/develop/home/models.py#L271)
**explanation**: an Article Page has some other page as a child (e.g., Poll) and I'm referring to it in the article body (StreamField) using Custom Page Chooser Block.

for simplicity, I have replicated the above-mentioned cases in another repo [here](https://github.com/sheralim012/wagtail-transfer-testing) 
databases for source and destination are also included in this repo too.
and I'm randomly (sometimes import is successful and sometimes it fails) getting `CircularDependencyException` for importing the same data
